/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Noom;

import dao.CustomerDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import model.Customer;

/**
 *
 * @author saharudseerakoon
 */
public class CustomerPanel extends javax.swing.JPanel {

    private ArrayList<Customer> customerList;
    String[] columnName = {"Customer_ID", "Name", "TelePhone", "Point", "Number of Purshase"};
    private CustomerTableModel model;
    Customer editedCustomer;

    /**
     * ,
     * Creates new form ProductPanel
     */
    public CustomerPanel() {
        initComponents();
        CustomerDao dao = new CustomerDao();
        initForm();
        loadTable(dao);
    }

    public void initForm() {
        JNo.setVisible(false);
        JName.setVisible(false);
        JTelePhone.setVisible(false);
        JPoint.setVisible(false);
        JPurshase.setVisible(false);
        btnSave.setVisible(false);
        btnCancel.setVisible(false);
        lblID.setVisible(false);
        txtName.setVisible(false);
        txtTelePhone.setVisible(false);
        txtPoint.setVisible(false);
        txtPurshase.setVisible(false);
        btnSave.setVisible(false);
        btnCancel.setVisible(false);
        btnBack.setVisible(false);


    }

    public void initFromTrue() {
        JNo.setVisible(true);
        JName.setVisible(true);
        JTelePhone.setVisible(true);
        JPoint.setVisible(true);
        JPurshase.setVisible(true);
        btnSave.setVisible(true);
        btnCancel.setVisible(true);
        lblID.setVisible(true);        
        txtName.setVisible(true);
        txtTelePhone.setVisible(true);
        txtPoint.setVisible(true);
        txtPurshase.setVisible(true);
        btnSave.setVisible(true);
        btnCancel.setVisible(true);
    }

    private void loadTable(CustomerDao dao) {
        customerList = dao.getAll();
        model = new CustomerTableModel(customerList);
        tblCustomer.setModel(model);
//        tblProduct.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent event) {
//                editedProduct = productList.get(tblProduct.getSelectedRow());
//                loadProductToForm();
//            }
//        });

    }

    public void loadCustomerToForm() {
        if (editedCustomer.getId() >= 0) {
            lblID.setText("" + editedCustomer.getId());
        }

        txtName.setText("" + editedCustomer.getName());
        txtTelePhone.setText("" + editedCustomer.getTel());
        txtPoint.setText("" + editedCustomer.getPoint());
        txtPurshase.setText("" + editedCustomer.getPurshase());
        initFromTrue();

    }

    public void loadFormToCustomer() {
       
        editedCustomer.setName(txtName.getText());
        editedCustomer.setTel(txtTelePhone.getText());
        editedCustomer.setPoint(Double.parseDouble(txtPoint.getText()));
        editedCustomer.setPurshase(Integer.parseInt(txtPurshase.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JNo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        JName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtTelePhone = new javax.swing.JTextField();
        JTelePhone = new javax.swing.JLabel();
        txtPoint = new javax.swing.JTextField();
        JPoint = new javax.swing.JLabel();
        txtPurshase = new javax.swing.JTextField();
        JPurshase = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        JSearch = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        scProctPane = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JNo.setText("No :");

        JName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JName.setText("Name ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 51, 204));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtTelePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelePhoneActionPerformed(evt);
            }
        });

        JTelePhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTelePhone.setText("TelePhone ");

        txtPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPointActionPerformed(evt);
            }
        });

        JPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPoint.setText(" Point ");

        txtPurshase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurshaseActionPerformed(evt);
            }
        });

        JPurshase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPurshase.setText("Number of Purshase ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTelePhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPurshase, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPurshase, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JNo)
                            .addComponent(JName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTelePhone)
                            .addComponent(txtTelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPoint)
                            .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPurshase)
                            .addComponent(txtPurshase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnSave))
                        .addGap(25, 25, 25))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 153, 0));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnAdd1.setBackground(new java.awt.Color(0, 51, 204));
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("Search");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        JSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JSearch.setText("Search Data");

        btnBack.setBackground(new java.awt.Color(204, 0, 51));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Clear");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(1, 1, 1)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd1)
                    .addComponent(JSearch)
                    .addComponent(btnBack))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.setSelectionBackground(new java.awt.Color(153, 153, 153));
        scProctPane.setViewportView(tblCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scProctPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scProctPane, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearEditForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        loadFormToCustomer();
        CustomerDao dao = new CustomerDao();
        if (editedCustomer.getId() >= 0) {
            dao.update(editedCustomer);
        } else {
            dao.add(editedCustomer);

        }
        refershTable();
        clearEditForm();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (tblCustomer.getSelectedRow() >= 0) {
            CustomerDao dao = new CustomerDao();
            editedCustomer = customerList.get(tblCustomer.getSelectedRow());
            dao.delete(editedCustomer.getId());
        }
        refershTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tblCustomer.getSelectedRow() >= 0) {

            editedCustomer = customerList.get(tblCustomer.getSelectedRow());
            loadCustomerToForm();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTelePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelePhoneActionPerformed

    private void txtPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPointActionPerformed

    private void txtPurshaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurshaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurshaseActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        btnBack.setVisible(true);
        search();
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CustomerDao dao = new CustomerDao();
        initForm();
        loadTable(dao);
        txtSearch.setText("");
        btnBack.setVisible(false);

    }//GEN-LAST:event_btnBackActionPerformed

    public void search() {
        CustomerDao dao = new CustomerDao();
        customerList = dao.getNAME(txtSearch.getText());

        System.out.println(customerList);
        if (customerList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Data !!!");
            loadTable(dao);
        } else {
            model = new CustomerTableModel(customerList);
            tblCustomer.setModel(model);
        }
    }

    public void refershTable() {
        CustomerDao dao = new CustomerDao();
        ArrayList<Customer> newList = dao.getAll();
        customerList.clear();
        customerList.addAll(newList);
        tblCustomer.revalidate();
        tblCustomer.repaint();
    }

    public void clearEditForm() {
        editedCustomer = null;
        lblID.setText("");
        txtName.setText("");
        txtTelePhone.setText("");
        txtPoint.setText("");
        txtPurshase.setText("");
        initForm();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JName;
    private javax.swing.JLabel JNo;
    private javax.swing.JLabel JPoint;
    private javax.swing.JLabel JPurshase;
    private javax.swing.JLabel JSearch;
    private javax.swing.JLabel JTelePhone;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblID;
    private javax.swing.JScrollPane scProctPane;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPoint;
    private javax.swing.JTextField txtPurshase;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelePhone;
    // End of variables declaration//GEN-END:variables

    private class CustomerTableModel extends AbstractTableModel {

        private final ArrayList<Customer> data;

        public CustomerTableModel(ArrayList<Customer> data) {
            this.data = data;
        }

        @Override
        public int getRowCount() {
            return this.data.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Customer customer = this.data.get(rowIndex);
           if (columnIndex == 0) {
                return customer.getId();
            }
            if (columnIndex == 1) {
                return customer.getName();
            }
            if (columnIndex == 2) {
                return customer.getTel();
            }
            if (columnIndex == 3) {
                return customer.getPoint();
            }
            if (columnIndex == 4) {
                return customer.getPurshase();
            }
            return "";


        }

        @Override
        public String getColumnName(int column) {
            return columnName[column];
        }

    }
}
